---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeview
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubeview
  template:
    metadata:
      labels:
        app: kubeview
    spec:
      containers:
        - name: kubeview
          image: ghcr.io/benc-uk/kubeview:0.1.31
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP