---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubeview
  namespace: default
spec:
  images:
    - name: ghcr.io/benc-uk/kubeview:0.1.31
      newName: ghcr.io/benc-uk/kubeview:0.1.31
      newTag: 0.1.31